package com.example.payment;

public enum BookingStatus {
    INITIATED,
    INVENTORY_CHECK_FAILED,
    SEAT_NOT_AVAILABLE,
    SEAT_HOLDED,
    SEAT_CONFIRMATION_FAILED,
    PRICING_SERVICE_UNAVAILABLE,
    PRICE_CALCULATED,
    PAYMENT_SERVICE_UNAVAILABLE,
    PAYMENT_RECORD_CREATION_FAILED,
    PAYMENT_PENDING,
    PAYMENT_FAILED,
    CONFIRMED,
    CANCELLED,
    COMPLETED
}
